### ISSUE TITLE
License ambiguity

### ISSUE THREAD

**Issue by AMDmi3** [mmottl/aifad#1]
Subj, source comments say

```
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
```

but COPYING.txt is GPLv3. It would be nice to bring these in sync.

**Comment by mmottl** [comment]
I've given it some thought and have decided to make the whole distribution LGPL-2.1 + OCaml linking exception.  The updated distribution is online.

**Comment by AMDmi3** [comment]
Thank you!

**Comment by AMDmi3** [comment]
Sorry, the ambiguity is still there. Now docs say LGPL2.1+, but source comments say LGPL2+

**Comment by mmottl** [comment]
Yeah, copy & paste in action.  I've updated the distribution.

**Comment by AMDmi3** [comment]
Yes, now fixed. Thank you again!
